import {STORE_KEY,normalizeProgress,filterQuestions,shuffle,interviewMix,setStatus,percent} from './core.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let questions=[],projects=[],progress=normalizeProgress(),page='dashboard',filters={},session=null,storageOK=true;
const opened=new Map();
try {progress=normalizeProgress(JSON.parse(localStorage.getItem(STORE_KEY)||'{}'));document.documentElement.dataset.theme=localStorage.getItem('interviewprep:theme')||'dark';}catch {storageOK=false;}
function notify(message){$('#notice').textContent=message;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').textContent='',3500);}
function save(){try{localStorage.setItem(STORE_KEY,JSON.stringify(progress));}catch{storageOK=false;notify('Storage unavailable. This session still works, but changes will not persist.');}updateLocalLabel();}
function updateLocalLabel(){$('.local-label').innerHTML=`<i></i> ${storageOK?'Saved on this device':'Session only · storage unavailable'}`;}
function themeLabel(){$('#theme').setAttribute('aria-label',`Switch to ${document.documentElement.dataset.theme==='dark'?'light':'dark'} theme`);}
$('#theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('interviewprep:theme',document.documentElement.dataset.theme);}catch{}themeLabel();};themeLabel();
$('#menu').onclick=()=>{const show=!document.body.classList.contains('menu-open');document.body.classList.toggle('menu-open',show);$('#menu').setAttribute('aria-expanded',String(show));};
const topicOrder=['Machine Learning','Deep Learning','NLP','LLMs','RAG','Computer Vision','Distributed Systems','Ray','Python','SQL','DSA','DBMS','Operating Systems','Computer Networks','Software Engineering','Behavioral'];
function navLink(label,target,icon,count=''){return `<a href="#${target}" class="nav-link ${page===target?'active':''}" ${page===target?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${esc(label)}${count!==''?`<small>${count}</small>`:''}</a>`;}
function sidebar(){$('#sidebar').innerHTML=`<a class="brand" href="#dashboard"><img src="./favicon.svg" alt="" width="32" height="32"><span>interview<span class="brand-light">prep</span><small>PRATHMESH'S WORKSPACE</small></span></a><nav><div class="nav-section">WORKSPACE</div>${navLink('Overview','dashboard','▦')}${navLink('Question bank','questions','≡',questions.length)}${navLink('Projects','projects','◇',projects.length)}${navLink('Bookmarks','bookmarks','☆',progress.bookmarks.length)}${navLink('Needs revision','revision','↺',progress.revision.length)}${navLink('Mock interviews','mock','▷')}<div class="nav-section">YOUR PROJECTS</div>${projects.slice(0,5).map(p=>navLink(p.name,'project/'+p.id,'·')).join('')}<div class="nav-section">TOPICS</div>${topicOrder.map(t=>navLink(t,'topic/'+encodeURIComponent(t),'·')).join('')}${navLink('Sources & coverage','sources','↗')}</nav><div class="profile"><span class="avatar">PN</span><div>Prathmesh Nikam<small>Personal interview handbook</small></div></div>`;}
function head(kicker,title,description,actions=''){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${actions?`<div class="head-actions">${actions}</div>`:''}</div>`;}
function button(label,action,style='',extra=''){return `<button class="btn ${style}" data-action="${action}" ${extra}>${label}</button>`;}
function progressLine(items){let n=percent(items,progress);return `<div class="progress-caption"><span>${items.filter(q=>progress.known.includes(q.id)).length} / ${items.length} mastered</span><span>${n}%</span></div><div class="progress-track"><div style="width:${n}%"></div></div>`;}
function projectCard(p,i){const qs=questions.filter(q=>q.project===p.id);return `<a class="project-card" href="#project/${p.id}"><div class="project-top"><span class="project-symbol symbol-${i%4}">${['⌘','⌁','⋈','↗'][i%4]}</span><span class="mono">${String(i+1).padStart(2,'0')} / PROJECT</span><span class="arrow">↗</span></div><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p><div class="tags">${p.tags.slice(1,3).map(t=>`<span>${esc(t)}</span>`).join('')}</div>${progressLine(qs)}</a>`;}
function dashboard(){const seen=progress.viewed.length,known=progress.known.length;return head('YOUR PERSONAL INTERVIEW HANDBOOK','Know your work. Own the interview.','Practice the concepts, decisions and tradeoffs behind your projects.',button('▷ Start studying','study','primary'))+`<section class="hero-grid"><div class="feature-panel"><div class="eyebrow accent">BUILT FROM YOUR REPOSITORIES</div><h2>Go beyond the definition.</h2><p>Explain why you chose it,<br>how you built it, and where it breaks.</p><div class="hero-actions"><a class="btn primary" href="#projects">Explore your projects <span>→</span></a>${button('15-question interview','random')}</div><div class="hero-path"><span>Understand</span><i>→</i><span>Explain</span><i>→</i><span>Defend</span></div></div><div class="session-panel"><div class="eyebrow">YOUR NEXT SESSION</div><span class="session-label">ML ENGINEER</span><h2>A little practice.<br>A sharper answer.</h2><p>15 questions across projects, ML, Python and system design.</p><div class="session-bottom"><span class="mono">~30 MIN <span> / </span> MIXED LEVELS</span>${button('Start →','random','text-btn')}</div></div></section><section class="stats" aria-label="Study statistics">${[[questions.length,'Questions to explore','≡'],[projects.length,'Project deep dives','◇'],[seen,'Answers viewed','◉'],[known,'Questions mastered','✓']].map(([v,l,i])=>`<div><span class="stat-icon">${i}</span><strong>${v}</strong><span>${l}</span></div>`).join('')}</section><div class="section-heading"><div><span class="eyebrow">START WITH WHAT YOU BUILT</span><h2>Your project playbook</h2></div><a href="#projects">All projects →</a></div><section class="project-grid">${projects.slice(0,6).map(projectCard).join('')}</section><div class="section-heading"><div><span class="eyebrow">BUILD THE FOUNDATIONS</span><h2>One concept at a time</h2></div><a href="#questions">Question bank →</a></div><section class="topic-grid">${['Ray','RAG','Machine Learning','Python','SQL','NLP'].map(t=>`<a class="topic-card" href="#topic/${encodeURIComponent(t)}"><div><h3>${t}</h3><span>${questions.filter(q=>q.topic===t&&!q.project).length} concept questions</span></div><span>→</span>${progressLine(questions.filter(q=>q.topic===t))}</a>`).join('')}</section><div class="evidence-banner"><span class="accent">◇</span><p><strong>Answers you can stand behind.</strong> Project answers link to repository evidence. FH-RAG implementation and personal results are marked where clarification is needed.</p><a href="#sources">Review sources →</a></div>`;}
function options(values,selected,all){return `<option value="">${all}</option>`+values.map(v=>{const [id,label]=Array.isArray(v)?v:[v,v];return `<option value="${esc(id)}" ${selected===id?'selected':''}>${esc(label)}</option>`;}).join('');}
function filterBar(){return `<div class="filter-panel"><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="Search questions, answers, projects, technologies…" value="${esc(filters.search||'')}" aria-label="Search all question content"><kbd>/</kbd></label><div class="filter-row"><label>Project<select data-filter="project">${options(projects.map(p=>[p.id,p.name]),filters.project,'All projects')}</select></label><label>Topic<select data-filter="topic">${options(topicOrder,filters.topic,'All topics')}</select></label><label>Difficulty<select data-filter="difficulty">${options(['Beginner','Intermediate','Advanced'],filters.difficulty,'All levels')}</select></label><label>Question type<select data-filter="type">${options(['Concept','Project','Coding','Architecture','Behavioral','Research','Follow-up'],filters.type,'All types')}</select></label>${button('Clear filters','clear','text-btn')}</div></div>`;}
function diagram(q){const d=q.diagram||projects.find(p=>p.id===q.project)?.diagram;if(!d)return '';return `<figure class="diagram"><figcaption>${q.project==='fh-rag'?'Conceptual design from supplied brief; implementation unverified':'Concept flow · read in order'}</figcaption><ol>${d.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></figure>`;}
function highlight(text){return esc(text).replace(/(&#39;.*?&#39;|&quot;.*?&quot;|\b(?:def|class|return|if|else|for|in|import|from|as|with|yield|None|True|False|await|async|assert|SELECT|FROM|WHERE|AS|GROUP|BY|HAVING|ORDER|DESC|JOIN|ON|WITH|PARTITION|OVER|CREATE|TABLE|INSERT|INTO|VALUES)\b|\b\d+\b)/g,m=>`<span class="syntax">${m}</span>`);}
function codeBlock(c){return `<div class="code-block"><div class="code-label">${esc(c.language)} ${button('Copy','copy','text-btn')}</div><pre><code>${highlight(c.text)}</code></pre></div>`;}
function answer(q,mode){if(mode==='followups')return `<h3>Interviewer may ask next</h3><ol class="followups">${q.followups.map(f=>`<li>${esc(f)}</li>`).join('')}</ol><p class="trap"><strong>Common mistake</strong>${esc(q.mistake)}</p>`;if(mode==='visual')return diagram(q);let text=q[mode]||q.standard;return `<div class="answer-copy">${text.split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('')}</div>${q.clarification?`<aside class="clarification"><strong>Evidence note</strong>${esc(q.clarification)}</aside>`:''}${mode==='deep'&&q.code?codeBlock(q.code):''}${mode==='deep'&&q.star?`<dl class="star">${Object.entries(q.star).map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`:''}<div class="source-links">${q.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">↗ ${esc(s.label)}</a>`).join('')}</div>${mode==='deep'?`<p class="trap"><strong>Common mistake</strong>${esc(q.mistake)}</p><h4>Related questions</h4>${q.related.map(id=>{const r=questions.find(x=>x.id===id);return r?`<a class="related" href="#question/${id}">${esc(r.question)} →</a>`:'';}).join('')}`:''}`;}
function card(q,study=false){const mode=opened.get(q.id),bookmarked=progress.bookmarks.includes(q.id),known=progress.known.includes(q.id),revision=progress.revision.includes(q.id);const visual=!!(q.diagram||q.project);return `<article class="question-card ${study?'study-card':''}" data-id="${q.id}"><div class="question-meta"><span class="mono">${esc(projects.find(p=>p.id===q.project)?.name||q.topic)}</span><span class="badge ${q.difficulty.toLowerCase()}">${q.difficulty}</span><span class="type-label">${q.type}</span>${known?'<span class="known-label">✓ Mastered</span>':revision?'<span class="revision-label">↺ Revision</span>':''}<button class="bookmark icon" data-action="bookmark" aria-label="${bookmarked?'Remove bookmark':'Bookmark question'}" aria-pressed="${bookmarked}">${bookmarked?'★':'☆'}</button></div><h2>${esc(q.question)}</h2><div class="tags">${q.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>${q.exercise?`<details class="exercise"><summary>Exercise schema, sample data & expected output</summary>${codeBlock({language:'sql',text:q.exercise.schema})}<strong>Expected output</strong><pre>${esc(q.exercise.columns)}\n${q.exercise.expected.map(r=>r.join(' | ')).map(esc).join('\n')}</pre></details>`:''}<div class="answer-tabs" aria-label="Answer options">${[['quick','Quick answer'],['standard',study?'Reveal answer':'Interview answer'],['deep','Deep dive'],['followups','Follow-ups'],...(visual?[['visual','Explain visually']]:[])].map(([k,l])=>`<button data-action="answer" data-mode="${k}" class="${mode===k?'selected':''}" aria-expanded="${mode===k}" aria-controls="answer-${q.id}">${l}</button>`).join('')}</div><div id="answer-${q.id}" class="answer ${mode?'revealed':''}" ${mode?'':'hidden'}>${mode?answer(q,mode):''}</div><div class="question-bottom"><span class="evidence-label">${q.project==='fh-rag'?'◌ Conceptual · needs clarification':q.sources.length?'◇ Repository-linked':'○ Concept practice'}</span><div>${button(known?'✓ Known':'Mark known','known',known?'selected':'text-btn')}${button(revision?'↺ Revising':'Needs revision','revision',revision?'selected':'text-btn')}</div></div>${study||mode==='deep'?`<details class="notes"><summary>Your notes · saved on this device</summary><label for="notes-${q.id}">Add your own implementation details, results or spoken answer.</label><textarea id="notes-${q.id}" data-note="${q.id}" rows="4" placeholder="What I personally implemented…">${esc(progress.notes[q.id]||'')}</textarea></details>`:''}</article>`;}
function results(){const list=filterQuestions(questions,filters,progress);return `<div class="results-heading"><span><b>${list.length}</b> questions <span class="muted">· answers hidden until you’re ready</span></span>${button('Study these questions →','study','text-btn',list.length?'':'disabled')}</div>${list.length?list.map(q=>card(q)).join(''):`<div class="empty"><span>⌕</span><h2>No questions here yet</h2><p>${filters.status==='bookmarks'?'Bookmark questions with the star to build your own study set.':filters.status==='revision'?'Mark a question “Needs revision” to return to it here.':'Try a broader search or clear the filters.'}</p>${button('Browse all questions','clear','primary')}</div>`}`;}
function bank(title='Question bank',description='Find a question. Try your answer. Then compare.') {return head('PRACTICE WITH PURPOSE',title,description)+filterBar()+`<section id="results" aria-live="polite">${results()}</section>`;}
function mock(){return head('PRACTICE THE CONVERSATION','Your next interview starts here.','Answer aloud before revealing the guide. Use follow-ups to go beyond rehearsed definitions.')+`<div class="mock-grid"><section class="mock-card featured"><span class="eyebrow accent">BALANCED RANDOM SESSION</span><h2>ML Engineer</h2><p>15 questions · approximately 30 minutes</p><ul><li>3 project + 3 machine learning</li><li>2 deep learning + 2 RAG / LLM</li><li>2 Python + 1 SQL</li><li>1 distributed / Ray + 1 behavioral</li></ul>${button('Generate interview →','random','primary')}</section>${projects.slice(0,5).map(p=>`<section class="mock-card"><span class="eyebrow">PROJECT DEFENSE</span><h2>${esc(p.name)}</h2><p>Work through project questions, then rehearse each interviewer follow-up in sequence.</p><span class="mono">${questions.filter(q=>q.project===p.id).length} BASE QUESTIONS</span>${button('Start project interview →','project-mock','',`data-project="${p.id}"`)}</section>`).join('')}</div>`;}
function startSession(list,label,follow=false){if(!list.length){notify('Choose at least one matching question first.');return;}session={items:follow?list.flatMap(q=>[{id:q.id},...q.followups.map(f=>({id:q.id,prompt:f}))]):list.map(q=>({id:q.id})),index:0,label,started:Date.now()};opened.clear();location.hash='study';if(page==='study')render();}
function study(){if(!session)return head('FOCUSED PRACTICE','Ready when you are.','Choose a study set or start a balanced interview.')+button('Start 15-question interview','random','primary');if(session.index>=session.items.length)return head('SESSION COMPLETE','Good work. Keep the hard ones close.',`${session.items.length} prompts completed. Mastery reflects your own ratings, not an automated score.`)+`<section class="completion"><h2>${esc(session.label)}</h2><p>${Math.max(1,Math.round((Date.now()-session.started)/60000))} minutes of practice</p><p>Review uncertain answers and add evidence to your personal notes.</p><a class="btn primary" href="#revision">Review difficult questions →</a><a class="btn" href="#dashboard">Back to overview</a></section>`;const item=session.items[session.index],q=questions.find(x=>x.id===item.id);return `<div class="study-header"><a href="#questions">← Exit study</a><span class="mono">${esc(session.label)}</span><span>${session.index+1} / ${session.items.length}</span></div><div class="progress-track session-progress"><div style="width:${session.index/session.items.length*100}%"></div></div>${item.prompt?`<section class="interviewer"><div class="eyebrow accent">INTERVIEWER FOLLOW-UP</div><h1>${esc(item.prompt)}</h1><p>Answer aloud. The parent answer below provides context; add your reasoning and check its sources.</p></section>`:''}${card(q,true)}<div class="study-controls">${button('← Previous','previous','',session.index===0?'disabled':'')}<span class="muted">Reveal only after trying your answer.</span>${button(session.index===session.items.length-1?'Finish session ✓':'Next question →','next','primary')}</div>`;}
function sources(){return head('EVIDENCE BEFORE CONFIDENCE','Sources & coverage','Repository snapshot reviewed 13 September 2026. Source links pin the inspected revision where available.')+`<div class="evidence-banner"><p><strong>Read the claim boundary.</strong> Source code supports behavior; it does not prove personal authorship, benchmark outcomes or production deployment. Proposed improvements are phrased conditionally.</p></div><div class="source-list">${projects.map(p=>`<section class="source-card"><h2>${esc(p.name)}</h2><p>${esc(p.summary)}</p>${p.notice?`<p class="clarification">${esc(p.notice)}</p>`:''}<div class="source-links">${p.sourceFiles.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">↗ ${esc(s.label)}</a>`).join('')}</div><a href="#project/${p.id}">Study project →</a></section>`).join('')}</div><section class="source-card"><h2>Your data stays in this browser</h2><p>Bookmarks, viewed answers, self-rated mastery, revision flags and notes are saved locally. Export a backup before clearing browser data. No account or backend is required.</p>${button('Export progress','export')}${button('Import progress','import')}<input id="import-file" type="file" accept="application/json" hidden></section><section class="source-card"><h2>Repository audit</h2><p>The audit includes repository inventory, exclusions, known discrepancies and coverage details.</p><a href="https://github.com/Prathmesh333/InterviewPrep/blob/feat/interview-handbook/docs/REPOSITORY_AUDIT.md">Read the full audit ↗</a></section>`;}
function render(){sidebar();document.body.classList.toggle('studying',page==='study');let content='';if(page==='dashboard')content=dashboard();else if(page==='projects')content=head('YOUR ENGINEERING EXPERIENCE','The project playbook','Start with the system you built, then follow the concepts beneath it.')+`<section class="project-grid">${projects.map(projectCard).join('')}</section>`;else if(page==='mock')content=mock();else if(page==='study')content=study();else if(page==='sources')content=sources();else if(page.startsWith('question/')){const q=questions.find(q=>q.id===page.split('/')[1]);content=q?head('QUESTION DETAIL',q.topic,'A focused view of one question, its evidence and related concepts.')+card(q):head('NOT FOUND','Question unavailable','Return to the question bank to continue.')+'<a href="#questions">Question bank →</a>';}else if(page.startsWith('project/')){const p=projects.find(p=>p.id===page.split('/')[1]);content=p?head('PROJECT PLAYBOOK',p.name,p.summary,button('▷ Study project','study','primary'))+(p.notice?`<p class="clarification">${esc(p.notice)}</p>`:'')+filterBar()+`<section id="results">${results()}</section>`:head('NOT FOUND','Project unavailable','Choose a project from the sidebar.');}else content=bank(page==='bookmarks'?'Your bookmarks':page==='revision'?'Needs revision':page.startsWith('topic/')?decodeURIComponent(page.slice(6)):'Question bank');$('#main').innerHTML=content;$('#crumb').textContent=page==='dashboard'?'Overview':page.split('/')[0].replace(/^./,s=>s.toUpperCase());updateLocalLabel();}
function route(){page=location.hash.slice(1)||'dashboard';filters={};if(page.startsWith('project/'))filters.project=page.split('/')[1];if(page.startsWith('topic/')){try{filters.topic=decodeURIComponent(page.slice(6));}catch{page='questions';}}if(page==='bookmarks')filters.status='bookmarks';if(page==='revision')filters.status='revision';document.body.classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');render();window.scrollTo(0,0);}
window.addEventListener('hashchange',route);
document.addEventListener('input',e=>{if(e.target.id==='search'){filters.search=e.target.value;$('#results').innerHTML=results();}if(e.target.dataset.note){progress.notes[e.target.dataset.note]=e.target.value;save();}});
document.addEventListener('change',async e=>{if(e.target.dataset.filter){filters[e.target.dataset.filter]=e.target.value;$('#results').innerHTML=results();}if(e.target.id==='import-file'&&e.target.files[0]){try{const f=e.target.files[0];if(f.size>2000000)throw Error();const raw=JSON.parse(await f.text());if(!raw||typeof raw!=='object'||!Array.isArray(raw.bookmarks)||!Array.isArray(raw.known))throw Error();progress=normalizeProgress(raw);const ids=new Set(questions.map(q=>q.id));for(const k of ['bookmarks','viewed','known','revision'])progress[k]=progress[k].filter(id=>ids.has(id));save();render();notify('Progress imported.');}catch{notify('That file is not a valid InterviewPrep progress backup.');}}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,article=b.closest('[data-id]'),q=article?questions.find(q=>q.id===article.dataset.id):null;
if(action==='answer'){const mode=b.dataset.mode;if(opened.get(q.id)===mode)opened.delete(q.id);else{opened.set(q.id,mode);if(['quick','standard','deep'].includes(mode)&&!progress.viewed.includes(q.id)){progress.viewed.push(q.id);save();}}article.outerHTML=card(q,page==='study');document.querySelector(`[data-id="${q.id}"] [data-mode="${mode}"]`)?.focus();}
if(action==='bookmark'){progress.bookmarks=progress.bookmarks.includes(q.id)?progress.bookmarks.filter(x=>x!==q.id):[...progress.bookmarks,q.id];save();if(filters.status==='bookmarks')$('#results').innerHTML=results();else article.outerHTML=card(q,page==='study');sidebar();}
if(action==='known'||action==='revision'){const key=action==='known'?'known':'revision';setStatus(progress,q.id,progress[key].includes(q.id)?null:key);save();if(filters.status==='revision')$('#results').innerHTML=results();else article.outerHTML=card(q,page==='study');sidebar();notify(key==='known'?'Mastery rating updated.':'Revision list updated.');}
if(action==='clear'){filters={};if(page==='bookmarks'||page==='revision'||page.startsWith('project/')||page.startsWith('topic/'))location.hash='questions';else render();}
if(action==='study')startSession(filterQuestions(questions,filters,progress),'Focused study');
if(action==='random')startSession(interviewMix(questions),'ML Engineer · 15 questions');
if(action==='project-mock')startSession(questions.filter(q=>q.project===b.dataset.project),projects.find(p=>p.id===b.dataset.project).name+' · project defense',true);
if(action==='next'||action==='previous'){session.index+=action==='next'?1:-1;opened.clear();render();window.scrollTo(0,0);$('#main').focus();}
if(action==='copy'){try{await navigator.clipboard.writeText(b.closest('.code-block').querySelector('code').textContent);notify('Code copied.');}catch{notify('Copy unavailable. Select the code to copy it manually.');}}
if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(progress,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='interviewprep-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
if(action==='import')$('#import-file').click();
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');}if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();if(!$('#search')){location.hash='questions';setTimeout(()=>$('#search')?.focus(),0);}else $('#search').focus();}});
try{const [manifest,ps]=await Promise.all([fetch('./data/manifest.json').then(r=>{if(!r.ok)throw Error();return r.json();}),fetch('./data/projects.json').then(r=>{if(!r.ok)throw Error();return r.json();})]);projects=ps;questions=(await Promise.all(manifest.map(f=>fetch('./data/'+f).then(r=>{if(!r.ok)throw Error();return r.json();})))).flat();const ids=new Set(questions.map(q=>q.id));for(const k of ['bookmarks','viewed','known','revision'])progress[k]=progress[k].filter(id=>ids.has(id));route();}catch(err){$('#main').innerHTML='<div class="empty"><h1>The handbook could not load.</h1><p>Refresh the page or check your connection. For local use, run npm run dev instead of opening the HTML file directly.</p><button class="btn" onclick="location.reload()">Try again</button></div>';console.error(err);}
